/* Generated by re2c 0.16 on Tue Sep 13 10:02:30 2016 */
#line 1 "url_parser.re"
#include <stdlib.h>
#include <string.h>
#include "url_parser.h"

const char *marker;
const char *url_str;

const char *YYMARKER;

#line 25 "url_parser.re"


int url_parse_scheme(URL *url)
{
    marker = url_str;

#line 20 "url_parser.c"
{
	unsigned char yych;
	yych = *(YYMARKER = url_str);
	switch (yych) {
	case 0x00:	goto yy3;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy5;
	default:	goto yy2;
	}
yy2:
#line 34 "url_parser.re"
	{ return 0; }
#line 83 "url_parser.c"
yy3:
	++url_str;
#line 33 "url_parser.re"
	{ url_str--; return 0; }
#line 88 "url_parser.c"
yy5:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy6;
	default:	goto yy8;
	}
yy6:
	url_str = YYMARKER;
	goto yy2;
yy7:
	++url_str;
	yych = *url_str;
yy8:
	switch (yych) {
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy7;
	case ':':	goto yy9;
	default:	goto yy6;
	}
yy9:
	++url_str;
#line 35 "url_parser.re"
	{
        int len = url_str - marker - 1;
        url->scheme = get_token(len);
        return 1;
    }
#line 180 "url_parser.c"
}
#line 40 "url_parser.re"

}

void url_parse_authority_userinfo (URL *url)
{
    marker = url_str;

#line 190 "url_parser.c"
{
	unsigned char yych;
	yych = *(YYMARKER = url_str);
	switch (yych) {
	case 0x00:	goto yy14;
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy16;
	case '%':	goto yy19;
	case '@':	goto yy20;
	default:	goto yy13;
	}
yy13:
#line 50 "url_parser.re"
	{ return; }
#line 281 "url_parser.c"
yy14:
	++url_str;
#line 49 "url_parser.re"
	{ url_str--; return; }
#line 286 "url_parser.c"
yy16:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy16;
	case '%':	goto yy19;
	case '@':	goto yy20;
	default:	goto yy18;
	}
yy18:
	url_str = YYMARKER;
	goto yy13;
yy19:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy22;
	default:	goto yy18;
	}
yy20:
	++url_str;
#line 51 "url_parser.re"
	{
        int len = url_str - marker - 1;
        char* userinfo = get_token(len);
        url->userinfo = userinfo;
        return;
    }
#line 413 "url_parser.c"
yy22:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy16;
	default:	goto yy18;
	}
}
#line 57 "url_parser.re"

}

void url_parse_authority_host (URL *url)
{
    marker = url_str;
    int incr = 0;

#line 452 "url_parser.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *(YYMARKER = url_str);
	switch (yych) {
	case 0x00:	goto yy26;
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy28;
	case '%':	goto yy31;
	case '0':	goto yy33;
	case '1':	goto yy34;
	case '2':	goto yy35;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	case '[':	goto yy37;
	default:	goto yy25;
	}
yy25:
#line 90 "url_parser.re"
	{ return; }
#line 543 "url_parser.c"
yy26:
	++url_str;
#line 89 "url_parser.re"
	{ url_str--; return; }
#line 548 "url_parser.c"
yy28:
	yyaccept = 1;
	YYMARKER = ++url_str;
	yych = *url_str;
yy29:
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy28;
	case '%':	goto yy31;
	default:	goto yy30;
	}
yy30:
#line 105 "url_parser.re"
	{
        url->host->type = REGNAME;
        goto host;
    }
#line 641 "url_parser.c"
yy31:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy38;
	default:	goto yy32;
	}
yy32:
	url_str = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy25;
	case 1: 	goto yy30;
	default:	goto yy113;
	}
yy33:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy39;
	default:	goto yy29;
	}
yy34:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy39;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	default:	goto yy29;
	}
yy35:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy39;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy36;
	case '5':	goto yy40;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	default:	goto yy29;
	}
yy36:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy39;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	default:	goto yy29;
	}
yy37:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':	goto yy41;
	case ':':	goto yy42;
	case 'f':	goto yy43;
	case 'v':	goto yy44;
	default:	goto yy32;
	}
yy38:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy28;
	default:	goto yy32;
	}
yy39:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '0':	goto yy45;
	case '1':	goto yy46;
	case '2':	goto yy47;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy48;
	default:	goto yy29;
	}
yy40:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy39;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy33;
	default:	goto yy29;
	}
yy41:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy49;
	case ':':	goto yy50;
	default:	goto yy32;
	}
yy42:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy51;
	default:	goto yy32;
	}
yy43:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':	goto yy49;
	case ':':	goto yy50;
	case 'e':	goto yy52;
	default:	goto yy32;
	}
yy44:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy32;
	default:	goto yy54;
	}
yy45:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy55;
	default:	goto yy29;
	}
yy46:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy55;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy48;
	default:	goto yy29;
	}
yy47:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy55;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy48;
	case '5':	goto yy56;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy45;
	default:	goto yy29;
	}
yy48:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy55;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy45;
	default:	goto yy29;
	}
yy49:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy57;
	case ':':	goto yy50;
	default:	goto yy32;
	}
yy50:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy58;
	case ':':	goto yy59;
	default:	goto yy32;
	}
yy51:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy60;
	case '1':	goto yy61;
	case '2':	goto yy62;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy63;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':	goto yy64;
	case ']':	goto yy65;
	case 'f':	goto yy67;
	default:	goto yy32;
	}
yy52:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy57;
	case '8':	goto yy68;
	case ':':	goto yy50;
	default:	goto yy32;
	}
yy53:
	++url_str;
	yych = *url_str;
yy54:
	switch (yych) {
	case '.':	goto yy69;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy53;
	default:	goto yy32;
	}
yy55:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '0':	goto yy70;
	case '1':	goto yy71;
	case '2':	goto yy72;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy73;
	default:	goto yy29;
	}
yy56:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy55;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy45;
	default:	goto yy29;
	}
yy57:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy74;
	case ':':	goto yy50;
	default:	goto yy32;
	}
yy58:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy75;
	case ':':	goto yy76;
	default:	goto yy32;
	}
yy59:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy77;
	case '1':	goto yy78;
	case '2':	goto yy79;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy80;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy81;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy60:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy83;
	case ':':	goto yy84;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy61:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy85;
	case ':':	goto yy84;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy83;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy62:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy85;
	case '5':	goto yy86;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy87;
	case ':':	goto yy84;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy83;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy63:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy87;
	case ':':	goto yy84;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy83;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy64:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy83;
	case ':':	goto yy84;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy65:
	++url_str;
#line 95 "url_parser.re"
	{
        url->host->type = IPV6ADDR;
        incr = 1;
        goto host;
    }
#line 1359 "url_parser.c"
yy67:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':	goto yy83;
	case ':':	goto yy84;
	case ']':	goto yy65;
	case 'f':	goto yy88;
	default:	goto yy32;
	}
yy68:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy89;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy74;
	case ':':	goto yy50;
	default:	goto yy32;
	}
yy69:
	yych = *++url_str;
	switch (yych) {
	case ']':	goto yy32;
	default:	goto yy91;
	}
yy70:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy92;
	default:	goto yy29;
	}
yy71:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy92;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy73;
	default:	goto yy29;
	}
yy72:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy92;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy73;
	case '5':	goto yy93;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy29;
	}
yy73:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy92;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy29;
	}
yy74:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy50;
	default:	goto yy32;
	}
yy75:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy94;
	case ':':	goto yy76;
	default:	goto yy32;
	}
yy76:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy95;
	case ':':	goto yy96;
	default:	goto yy32;
	}
yy77:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy97;
	case ':':	goto yy98;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy78:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy99;
	case ':':	goto yy98;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy97;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy79:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy99;
	case '5':	goto yy100;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy101;
	case ':':	goto yy98;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy97;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy80:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy101;
	case ':':	goto yy98;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy97;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy81:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy97;
	case ':':	goto yy98;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy82:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy102;
	case '1':	goto yy103;
	case '2':	goto yy104;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy105;
	default:	goto yy32;
	}
yy83:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy106;
	case ':':	goto yy84;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy84:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy81;
	default:	goto yy32;
	}
yy85:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy107;
	case ':':	goto yy84;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy106;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy86:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy107;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy106;
	case ':':	goto yy84;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy87:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy106;
	case ':':	goto yy84;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy88:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':	goto yy106;
	case ':':	goto yy84;
	case ']':	goto yy65;
	case 'f':	goto yy108;
	default:	goto yy32;
	}
yy89:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy109;
	default:	goto yy32;
	}
yy90:
	++url_str;
	yych = *url_str;
yy91:
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy90;
	case ']':	goto yy110;
	default:	goto yy32;
	}
yy92:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '0':	goto yy112;
	case '1':	goto yy114;
	case '2':	goto yy115;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy116;
	default:	goto yy29;
	}
yy93:
	yyaccept = 1;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '.':	goto yy92;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy70;
	default:	goto yy29;
	}
yy94:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy117;
	case ':':	goto yy76;
	default:	goto yy32;
	}
yy95:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy118;
	case ':':	goto yy119;
	default:	goto yy32;
	}
yy96:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy120;
	case '1':	goto yy121;
	case '2':	goto yy122;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy123;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy124;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy97:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy125;
	case ':':	goto yy98;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy98:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy124;
	default:	goto yy32;
	}
yy99:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy126;
	case ':':	goto yy98;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy125;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy100:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy126;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy125;
	case ':':	goto yy98;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy101:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy125;
	case ':':	goto yy98;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy102:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy127;
	default:	goto yy32;
	}
yy103:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy127;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy105;
	default:	goto yy32;
	}
yy104:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy127;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy105;
	case '5':	goto yy128;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy102;
	default:	goto yy32;
	}
yy105:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy127;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy102;
	default:	goto yy32;
	}
yy106:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy129;
	case ':':	goto yy84;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy107:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy129;
	case ':':	goto yy84;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy108:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':	goto yy129;
	case ':':	goto yy84;
	case ']':	goto yy65;
	case 'f':	goto yy130;
	default:	goto yy32;
	}
yy109:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy58;
	case ':':	goto yy132;
	default:	goto yy32;
	}
yy110:
	++url_str;
#line 100 "url_parser.re"
	{
        url->host->type = IPVFUTUR;
        incr = 1;
        goto host;
    }
#line 2412 "url_parser.c"
yy112:
	yyaccept = 2;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy29;
	default:	goto yy113;
	}
yy113:
#line 91 "url_parser.re"
	{
        url->host->type = IPV4ADDR;
        goto host;
    }
#line 2503 "url_parser.c"
yy114:
	yyaccept = 2;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy29;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy116;
	default:	goto yy113;
	}
yy115:
	yyaccept = 2;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy29;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy116;
	case '5':	goto yy133;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy112;
	default:	goto yy113;
	}
yy116:
	yyaccept = 2;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy29;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy112;
	default:	goto yy113;
	}
yy117:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy76;
	default:	goto yy32;
	}
yy118:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy134;
	case ':':	goto yy119;
	default:	goto yy32;
	}
yy119:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy135;
	case ':':	goto yy136;
	default:	goto yy32;
	}
yy120:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy137;
	case ':':	goto yy138;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy121:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy139;
	case ':':	goto yy138;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy137;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy122:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy139;
	case '5':	goto yy140;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy141;
	case ':':	goto yy138;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy137;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy123:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy141;
	case ':':	goto yy138;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy137;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy124:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy137;
	case ':':	goto yy138;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy125:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy142;
	case ':':	goto yy98;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy126:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy142;
	case ':':	goto yy98;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy127:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy143;
	case '1':	goto yy144;
	case '2':	goto yy145;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy146;
	default:	goto yy32;
	}
yy128:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy127;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy102;
	default:	goto yy32;
	}
yy129:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy84;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy130:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy147;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy131:
	yych = *++url_str;
	switch (yych) {
	case ']':	goto yy32;
	default:	goto yy149;
	}
yy132:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy150;
	case '1':	goto yy151;
	case '2':	goto yy152;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy153;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy154;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy133:
	yyaccept = 2;
	yych = *(YYMARKER = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '6':
	case '7':
	case '8':
	case '9':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy29;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy112;
	default:	goto yy113;
	}
yy134:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy155;
	case ':':	goto yy119;
	default:	goto yy32;
	}
yy135:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy156;
	case ':':	goto yy157;
	default:	goto yy32;
	}
yy136:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy158;
	case '1':	goto yy159;
	case '2':	goto yy160;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy161;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy162;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy137:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy163;
	case ':':	goto yy138;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy138:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy162;
	default:	goto yy32;
	}
yy139:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy164;
	case ':':	goto yy138;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy163;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy140:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy164;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy163;
	case ':':	goto yy138;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy141:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy163;
	case ':':	goto yy138;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy142:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy98;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy143:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy165;
	default:	goto yy32;
	}
yy144:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy165;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy146;
	default:	goto yy32;
	}
yy145:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy165;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy146;
	case '5':	goto yy166;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy143;
	default:	goto yy32;
	}
yy146:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy165;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy143;
	default:	goto yy32;
	}
yy147:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy167;
	case '1':	goto yy78;
	case '2':	goto yy79;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy80;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy81;
	default:	goto yy32;
	}
yy148:
	++url_str;
	yych = *url_str;
yy149:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy148;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy150:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy168;
	case ':':	goto yy169;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy151:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy170;
	case ':':	goto yy169;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy168;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy152:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy170;
	case '5':	goto yy171;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy172;
	case ':':	goto yy169;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy168;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy153:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy172;
	case ':':	goto yy169;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy168;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy154:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy168;
	case ':':	goto yy169;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy155:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy119;
	default:	goto yy32;
	}
yy156:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy173;
	case ':':	goto yy157;
	default:	goto yy32;
	}
yy157:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy174;
	case ':':	goto yy175;
	default:	goto yy32;
	}
yy158:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy176;
	case ':':	goto yy177;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy159:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy178;
	case ':':	goto yy177;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy176;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy160:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy178;
	case '5':	goto yy179;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy180;
	case ':':	goto yy177;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy176;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy161:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy180;
	case ':':	goto yy177;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy176;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy162:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy176;
	case ':':	goto yy177;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy163:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy181;
	case ':':	goto yy138;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy164:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy181;
	case ':':	goto yy138;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy165:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy182;
	case '1':	goto yy183;
	case '2':	goto yy184;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy185;
	default:	goto yy32;
	}
yy166:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy165;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy143;
	default:	goto yy32;
	}
yy167:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy97;
	case ':':	goto yy186;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy168:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy187;
	case ':':	goto yy169;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy169:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy188;
	default:	goto yy32;
	}
yy170:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy189;
	case ':':	goto yy169;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy187;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy171:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy189;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy187;
	case ':':	goto yy169;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy172:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy187;
	case ':':	goto yy169;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy173:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy190;
	case ':':	goto yy157;
	default:	goto yy32;
	}
yy174:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy191;
	case ':':	goto yy192;
	default:	goto yy32;
	}
yy175:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy193;
	case '1':	goto yy194;
	case '2':	goto yy195;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy196;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy197;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy176:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy198;
	case ':':	goto yy177;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy177:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy197;
	default:	goto yy32;
	}
yy178:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy199;
	case ':':	goto yy177;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy198;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy179:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy199;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy198;
	case ':':	goto yy177;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy180:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy198;
	case ':':	goto yy177;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy181:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy138;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy182:
	yych = *++url_str;
	switch (yych) {
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy183:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy185;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy184:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy185;
	case '5':	goto yy200;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy182;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy185:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy182;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy186:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy201;
	case '1':	goto yy121;
	case '2':	goto yy122;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy123;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy124;
	default:	goto yy32;
	}
yy187:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy202;
	case ':':	goto yy169;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy188:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy203;
	case ':':	goto yy204;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy189:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy202;
	case ':':	goto yy169;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy190:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy157;
	default:	goto yy32;
	}
yy191:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy205;
	case ':':	goto yy192;
	default:	goto yy32;
	}
yy192:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy206;
	case ':':	goto yy207;
	default:	goto yy32;
	}
yy193:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy208;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy194:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy210;
	case ':':	goto yy209;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy208;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy195:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy210;
	case '5':	goto yy211;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy212;
	case ':':	goto yy209;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy208;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy196:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy212;
	case ':':	goto yy209;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy208;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy197:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy208;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy198:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy213;
	case ':':	goto yy177;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy199:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy213;
	case ':':	goto yy177;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy200:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy182;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy201:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy137;
	case ':':	goto yy214;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy202:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case ':':	goto yy169;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy203:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy215;
	case ':':	goto yy204;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy204:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy216;
	default:	goto yy32;
	}
yy205:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy217;
	case ':':	goto yy192;
	default:	goto yy32;
	}
yy206:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy218;
	case ':':	goto yy219;
	default:	goto yy32;
	}
yy207:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy220;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy208:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy221;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy209:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy220;
	default:	goto yy32;
	}
yy210:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy222;
	case ':':	goto yy209;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy221;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy211:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy222;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy221;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy212:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy221;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy213:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy177;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy214:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy223;
	case '1':	goto yy159;
	case '2':	goto yy160;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy161;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy162;
	default:	goto yy32;
	}
yy215:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy224;
	case ':':	goto yy204;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy216:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy225;
	case ':':	goto yy226;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy217:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy192;
	default:	goto yy32;
	}
yy218:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy227;
	case ':':	goto yy219;
	default:	goto yy32;
	}
yy219:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy228;
	case ':':	goto yy229;
	default:	goto yy32;
	}
yy220:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy230;
	case ':':	goto yy231;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy221:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy232;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy222:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy232;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy223:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy176;
	case ':':	goto yy233;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy224:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case ':':	goto yy204;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy225:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy234;
	case ':':	goto yy226;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy226:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy235;
	default:	goto yy32;
	}
yy227:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy236;
	case ':':	goto yy219;
	default:	goto yy32;
	}
yy228:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy237;
	case ':':	goto yy238;
	default:	goto yy32;
	}
yy229:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy239;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy230:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy240;
	case ':':	goto yy231;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy231:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy239;
	default:	goto yy32;
	}
yy232:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy233:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy241;
	case '1':	goto yy194;
	case '2':	goto yy195;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy196;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy197;
	default:	goto yy32;
	}
yy234:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy242;
	case ':':	goto yy226;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy235:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy243;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy236:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy219;
	default:	goto yy32;
	}
yy237:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy244;
	case ':':	goto yy238;
	default:	goto yy32;
	}
yy238:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy239;
	case ':':	goto yy182;
	default:	goto yy32;
	}
yy239:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy245;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy240:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy246;
	case ':':	goto yy231;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy241:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy208;
	case ':':	goto yy247;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy242:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case ':':	goto yy226;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy243:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy248;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy244:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy249;
	case ':':	goto yy238;
	default:	goto yy32;
	}
yy245:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy250;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy246:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy231;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy247:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy251;
	case '1':	goto yy252;
	case '2':	goto yy253;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy254;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy220;
	default:	goto yy32;
	}
yy248:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy255;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy249:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy238;
	default:	goto yy32;
	}
yy250:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy182;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy251:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy230;
	case ':':	goto yy231;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy252:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy256;
	case ':':	goto yy231;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy230;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy253:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy256;
	case '5':	goto yy257;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy258;
	case ':':	goto yy231;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy230;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy254:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy258;
	case ':':	goto yy231;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy230;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy255:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy131;
	case ':':	goto yy209;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy256:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy259;
	case ':':	goto yy231;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy240;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy257:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy259;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy240;
	case ':':	goto yy231;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy258:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy240;
	case ':':	goto yy231;
	case ']':	goto yy65;
	default:	goto yy32;
	}
yy259:
	++url_str;
	switch ((yych = *url_str)) {
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy246;
	case ':':	goto yy231;
	case ']':	goto yy65;
	default:	goto yy32;
	}
}
#line 109 "url_parser.re"

host:;
    int len = url_str - marker;

    if (incr) {
        len -= 2;
        marker++;
    }

    char* host = get_token(len);
    strncpy (url->host->name, host, HOST_MAX_LEN < len + 1 ? HOST_MAX_LEN : len + 1);
    free (host);
}

void url_parse_authority_port (URL *url)
{
    marker = url_str;

#line 6402 "url_parser.c"
{
	unsigned char yych;
	yych = *url_str;
	switch (yych) {
	case 0x00:	goto yy263;
	case ':':	goto yy265;
	default:	goto yy262;
	}
yy262:
#line 129 "url_parser.re"
	{ return; }
#line 6414 "url_parser.c"
yy263:
	++url_str;
#line 128 "url_parser.re"
	{ url_str--; return; }
#line 6419 "url_parser.c"
yy265:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy265;
	default:	goto yy267;
	}
yy267:
#line 130 "url_parser.re"
	{
        marker++;
        int len = url_str - marker;
        char* port = get_token(len);
        url->port = atoi(port);
        free(port);
    }
#line 6445 "url_parser.c"
}
#line 137 "url_parser.re"

}

int url_parse_authority (URL *url)
{

#line 6454 "url_parser.c"
{
	unsigned char yych;
	yych = *(YYMARKER = url_str);
	switch (yych) {
	case 0x00:	goto yy271;
	case '/':	goto yy273;
	default:	goto yy270;
	}
yy270:
#line 144 "url_parser.re"
	{ return 0; }
#line 6466 "url_parser.c"
yy271:
	++url_str;
#line 143 "url_parser.re"
	{ url_str--; return 0; }
#line 6471 "url_parser.c"
yy273:
	yych = *++url_str;
	switch (yych) {
	case '/':	goto yy275;
	default:	goto yy274;
	}
yy274:
	url_str = YYMARKER;
	goto yy270;
yy275:
	++url_str;
#line 145 "url_parser.re"
	{
        goto authority;
    }
#line 6487 "url_parser.c"
}
#line 148 "url_parser.re"


authority:;
    url_parse_authority_userinfo(url);
    url_parse_authority_host(url);
    url_parse_authority_port(url);

    if (url->host->type != UNKNOWN) {
        return 1;
    } else {
        if (url->userinfo) free(url->userinfo);
        memset(&url->host->type, 0, sizeof(url->host->type));
        url->port = 0;
        return 0;
    }
}

int url_parse_path (URL *url)
{
    marker = url_str;

#line 6511 "url_parser.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *(YYMARKER = url_str);
	switch (yych) {
	case 0x00:	goto yy280;
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy282;
	case '%':	goto yy285;
	default:	goto yy279;
	}
yy279:
#line 179 "url_parser.re"
	{ return 0; }
#line 6604 "url_parser.c"
yy280:
	++url_str;
#line 178 "url_parser.re"
	{ url_str--; return 0; }
#line 6609 "url_parser.c"
yy282:
	yyaccept = 1;
	YYMARKER = ++url_str;
	yych = *url_str;
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy282;
	case '%':	goto yy285;
	default:	goto yy284;
	}
yy284:
#line 180 "url_parser.re"
	{
        int len = url_str - marker;
        url->path = get_token(len);
        return 1;
    }
#line 6705 "url_parser.c"
yy285:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy287;
	default:	goto yy286;
	}
yy286:
	url_str = YYMARKER;
	if (yyaccept == 0) {
		goto yy279;
	} else {
		goto yy284;
	}
yy287:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy282;
	default:	goto yy286;
	}
}
#line 185 "url_parser.re"

}

void url_parse_query_frag (URL *url)
{
query_frag:;
    marker = url_str;

#line 6779 "url_parser.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *url_str;
	switch (yych) {
	case 0x00:	goto yy291;
	case '#':	goto yy293;
	case '?':	goto yy296;
	default:	goto yy290;
	}
yy290:
#line 197 "url_parser.re"
	{ return; }
#line 6793 "url_parser.c"
yy291:
	++url_str;
#line 196 "url_parser.re"
	{ url_str--; return; }
#line 6798 "url_parser.c"
yy293:
	yyaccept = 0;
	YYMARKER = ++url_str;
	yych = *url_str;
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy293;
	case '%':	goto yy299;
	default:	goto yy295;
	}
yy295:
#line 204 "url_parser.re"
	{
        marker++;
        int len = url_str - marker;
        url->fragment = get_token(len);
        return;
    }
#line 6896 "url_parser.c"
yy296:
	yyaccept = 1;
	YYMARKER = ++url_str;
	yych = *url_str;
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy296;
	case '%':	goto yy301;
	default:	goto yy298;
	}
yy298:
#line 198 "url_parser.re"
	{
        marker++;
        int len = url_str - marker;
        url->query = get_token(len);
        goto query_frag;
    }
#line 6994 "url_parser.c"
yy299:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy302;
	default:	goto yy300;
	}
yy300:
	url_str = YYMARKER;
	if (yyaccept == 0) {
		goto yy295;
	} else {
		goto yy298;
	}
yy301:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy303;
	default:	goto yy300;
	}
yy302:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy293;
	default:	goto yy300;
	}
yy303:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy296;
	default:	goto yy300;
	}
}
#line 210 "url_parser.re"

}

int url_parse (const char *input, URL *url)
{
    int retval = 0;
    url_str = input;

    if (url_parse_scheme(url)) {
        url_parse_authority(url);
        url_parse_path(url);
        url_parse_query_frag(url);
        retval = 1;
    } else {
        if (url_parse_authority(url)) {
            url_parse_path(url);
            url_parse_query_frag(url);
            retval = 1;
        } else if (strlen(url_str) && url_parse_path(url)) {
            url_parse_query_frag(url);
            retval = 1;
        }
    }
    return retval;
}

URL *url_create ()
{
    URL *url = (URL*) malloc (sizeof(URL));
    url->host = (Host*) malloc (sizeof(Host));

    url->scheme   = NULL;
    url->userinfo = NULL;
    url->host->type = UNKNOWN;
    memset(&url->host->type, 0, sizeof(url->host->type));
    url->port = 0;
    url->path = NULL;
    url->query = NULL;
    url->fragment = NULL;

    return url;
}

void url_free (URL *url)
{
    if (url->scheme) free (url->scheme);
    if (url->userinfo) free (url->userinfo);
    if (url->host) free (url->host);
    if (url->path) free (url->path);
    if (url->query) free (url->query);
    if (url->fragment) free (url->fragment);
    free (url);
}

char * get_token(int len)
{
    char *res = (char *) malloc (len + 1);
    int i = 0;
    for (; i < len; i++) res[i] = marker[i];
    res[i] = '\0';
    return res;
}
