/* Generated by re2c 0.16 on Fri Sep  9 20:29:45 2016 */
#line 1 "url_parser.re"
#include <stdlib.h>
#include <string.h>
#include "url_parser.h"

int url_parse (const char *url_str, URL *url)
{
  const char *marker;
  const char *ctxmarker;
  const char *src = url_str;
  int pos = 0;

#line 15 "url_parser.c"
{
	unsigned char yych;
	yych = *url_str;
	switch (yych) {
	case 0x00:	goto yy2;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy6;
	default:	goto yy4;
	}
yy2:
	++url_str;
#line 63 "url_parser.re"
	{ return 0;}
#line 79 "url_parser.c"
yy4:
	++url_str;
yy5:
#line 62 "url_parser.re"
	{ --url_str; goto hier_part; }
#line 85 "url_parser.c"
yy6:
	yych = *(marker = ++url_str);
	switch (yych) {
	case '+':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy8;
	default:	goto yy5;
	}
yy7:
	++url_str;
	yych = *url_str;
yy8:
	switch (yych) {
	case '+':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy7;
	case ':':	goto yy10;
	default:	goto yy9;
	}
yy9:
	url_str = marker;
	goto yy5;
yy10:
	++url_str;
#line 64 "url_parser.re"
	{
    int len = url_str - src - 1;
    url->scheme = get_lex(src, &pos, len);
    pos++; // add ":"
    goto hier_part;
  }
#line 242 "url_parser.c"
}
#line 70 "url_parser.re"


hier_part:

#line 249 "url_parser.c"
{
	unsigned char yych;
	yych = *url_str;
	switch (yych) {
	case 0x00:	goto yy14;
	case '/':	goto yy18;
	default:	goto yy16;
	}
yy14:
	++url_str;
#line 75 "url_parser.re"
	{ return 0; }
#line 262 "url_parser.c"
yy16:
	++url_str;
yy17:
#line 74 "url_parser.re"
	{ --url_str; goto hier_part_host; }
#line 268 "url_parser.c"
yy18:
	yych = *++url_str;
	switch (yych) {
	case '/':	goto yy19;
	default:	goto yy17;
	}
yy19:
	++url_str;
#line 76 "url_parser.re"
	{ pos +=2; goto hier_part_authority; }
#line 279 "url_parser.c"
}
#line 77 "url_parser.re"


hier_part_authority:

#line 286 "url_parser.c"
{
	unsigned char yych;
	yych = *url_str;
	switch (yych) {
	case 0x00:	goto yy23;
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy27;
	case '%':	goto yy28;
	case '@':	goto yy29;
	default:	goto yy25;
	}
yy23:
	++url_str;
#line 82 "url_parser.re"
	{ return 0;}
#line 378 "url_parser.c"
yy25:
	++url_str;
yy26:
#line 81 "url_parser.re"
	{ url_str--; goto hier_part_host; }
#line 384 "url_parser.c"
yy27:
	yych = *(marker = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy32;
	default:	goto yy26;
	}
yy28:
	yych = *(marker = ++url_str);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy35;
	default:	goto yy26;
	}
yy29:
	++url_str;
#line 83 "url_parser.re"
	{
    int len = url_str - src - pos - 1; // unshift 1 char for "@"
    url->userinfo = get_lex(src, &pos, len);
    pos++; // shift for "@" char
    goto hier_part_host;
  }
#line 506 "url_parser.c"
yy31:
	++url_str;
	yych = *url_str;
yy32:
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy31;
	case '%':	goto yy34;
	case '@':	goto yy29;
	default:	goto yy33;
	}
yy33:
	url_str = marker;
	goto yy26;
yy34:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy35;
	default:	goto yy33;
	}
yy35:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy31;
	default:	goto yy33;
	}
}
#line 89 "url_parser.re"


hier_part_host:

#line 659 "url_parser.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *url_str;
	ctxmarker = url_str;
	switch (yych) {
	case 0x00:	goto yy38;
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy42;
	case '%':	goto yy45;
	case '/':	goto yy46;
	case '0':	goto yy48;
	case '1':	goto yy49;
	case '2':	goto yy50;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy51;
	case '[':	goto yy52;
	default:	goto yy40;
	}
yy38:
	++url_str;
#line 94 "url_parser.re"
	{ return 0;}
#line 753 "url_parser.c"
yy40:
	++url_str;
yy41:
#line 93 "url_parser.re"
	{ goto hier_part_path; }
#line 759 "url_parser.c"
yy42:
	yyaccept = 0;
	marker = ++url_str;
	yych = *url_str;
yy43:
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy42;
	case '%':	goto yy53;
	default:	goto yy44;
	}
yy44:
#line 127 "url_parser.re"
	{
    int len = url_str - src - pos;
    url->host->type = REGNAME;
    char *name = get_lex(src, &pos, len);
    strncpy (url->host->name, name, HOST_MAX_LEN < len + 1 ? HOST_MAX_LEN : len + 1);
    free (name);
    goto hier_part_port;
  }
#line 856 "url_parser.c"
yy45:
	yyaccept = 1;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy55;
	default:	goto yy41;
	}
yy46:
	++url_str;
	url_str = ctxmarker;
#line 95 "url_parser.re"
	{
    url->host->type = UNKNOWN;
    goto hier_part_path;
  }
#line 893 "url_parser.c"
yy48:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy56;
	default:	goto yy43;
	}
yy49:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy56;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy51;
	default:	goto yy43;
	}
yy50:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy56;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy51;
	case '5':	goto yy57;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy48;
	default:	goto yy43;
	}
yy51:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy56;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy48;
	default:	goto yy43;
	}
yy52:
	yyaccept = 1;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':	goto yy58;
	case ':':	goto yy59;
	case 'f':	goto yy60;
	case 'v':	goto yy61;
	default:	goto yy41;
	}
yy53:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy55;
	default:	goto yy54;
	}
yy54:
	url_str = marker;
	switch (yyaccept) {
	case 0: 	goto yy44;
	case 1: 	goto yy41;
	default:	goto yy127;
	}
yy55:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy42;
	default:	goto yy54;
	}
yy56:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '0':	goto yy62;
	case '1':	goto yy63;
	case '2':	goto yy64;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy65;
	default:	goto yy43;
	}
yy57:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy56;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy48;
	default:	goto yy43;
	}
yy58:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy66;
	case ':':	goto yy67;
	default:	goto yy54;
	}
yy59:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy68;
	default:	goto yy54;
	}
yy60:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':	goto yy66;
	case ':':	goto yy67;
	case 'e':	goto yy69;
	default:	goto yy54;
	}
yy61:
	yych = *++url_str;
	switch (yych) {
	case ']':	goto yy54;
	default:	goto yy70;
	}
yy62:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy72;
	default:	goto yy43;
	}
yy63:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy72;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy65;
	default:	goto yy43;
	}
yy64:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy72;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy65;
	case '5':	goto yy73;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy62;
	default:	goto yy43;
	}
yy65:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy72;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy62;
	default:	goto yy43;
	}
yy66:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy74;
	case ':':	goto yy67;
	default:	goto yy54;
	}
yy67:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy75;
	case ':':	goto yy76;
	default:	goto yy54;
	}
yy68:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy77;
	case '1':	goto yy78;
	case '2':	goto yy79;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy80;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':	goto yy81;
	case ']':	goto yy82;
	case 'f':	goto yy84;
	default:	goto yy54;
	}
yy69:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy74;
	case '8':	goto yy85;
	case ':':	goto yy67;
	default:	goto yy54;
	}
yy70:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case ']':	goto yy86;
	default:	goto yy70;
	}
yy72:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '0':	goto yy88;
	case '1':	goto yy89;
	case '2':	goto yy90;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy91;
	default:	goto yy43;
	}
yy73:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy72;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy62;
	default:	goto yy43;
	}
yy74:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy92;
	case ':':	goto yy67;
	default:	goto yy54;
	}
yy75:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy93;
	case ':':	goto yy94;
	default:	goto yy54;
	}
yy76:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy95;
	case '1':	goto yy96;
	case '2':	goto yy97;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy98;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy99;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy77:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy101;
	case ':':	goto yy102;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy78:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy103;
	case ':':	goto yy102;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy101;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy79:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy103;
	case '5':	goto yy104;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy105;
	case ':':	goto yy102;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy101;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy80:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy105;
	case ':':	goto yy102;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy101;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy81:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy101;
	case ':':	goto yy102;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy82:
	++url_str;
#line 117 "url_parser.re"
	{
    pos++; // shift "["
    int len = url_str - src - pos - 1; // skip "]"
    url->host->type = IPV6ADDR;
    char *name = get_lex(src, &pos, len);
    pos++;
    strncpy (url->host->name, name, HOST_MAX_LEN < len + 1 ? HOST_MAX_LEN : len + 1);
    free (name);
    goto hier_part_port;
  }
#line 1594 "url_parser.c"
yy84:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':	goto yy101;
	case ':':	goto yy102;
	case ']':	goto yy82;
	case 'f':	goto yy106;
	default:	goto yy54;
	}
yy85:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy107;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy92;
	case ':':	goto yy67;
	default:	goto yy54;
	}
yy86:
	++url_str;
#line 107 "url_parser.re"
	{
    pos++; // shift "["
    int len = url_str - src - pos - 1;
    url->host->type = IPVFUTUR;
    char *name = get_lex(src, &pos, len);
    pos++;
    strncpy (url->host->name, name, HOST_MAX_LEN < len + 1 ? HOST_MAX_LEN : len + 1);
    free (name);
    goto hier_part_port;
  }
#line 1665 "url_parser.c"
yy88:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy108;
	default:	goto yy43;
	}
yy89:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy108;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy91;
	default:	goto yy43;
	}
yy90:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy108;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy91;
	case '5':	goto yy109;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy88;
	default:	goto yy43;
	}
yy91:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy108;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy88;
	default:	goto yy43;
	}
yy92:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy67;
	default:	goto yy54;
	}
yy93:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy110;
	case ':':	goto yy94;
	default:	goto yy54;
	}
yy94:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy111;
	case ':':	goto yy112;
	default:	goto yy54;
	}
yy95:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy113;
	case ':':	goto yy114;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy96:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy115;
	case ':':	goto yy114;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy113;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy97:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy115;
	case '5':	goto yy116;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy117;
	case ':':	goto yy114;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy113;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy98:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy117;
	case ':':	goto yy114;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy113;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy99:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy113;
	case ':':	goto yy114;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy100:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy118;
	case '1':	goto yy119;
	case '2':	goto yy120;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy121;
	default:	goto yy54;
	}
yy101:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy122;
	case ':':	goto yy102;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy102:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy99;
	default:	goto yy54;
	}
yy103:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy123;
	case ':':	goto yy102;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy122;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy104:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy123;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy122;
	case ':':	goto yy102;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy105:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy122;
	case ':':	goto yy102;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy106:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':	goto yy122;
	case ':':	goto yy102;
	case ']':	goto yy82;
	case 'f':	goto yy124;
	default:	goto yy54;
	}
yy107:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy125;
	default:	goto yy54;
	}
yy108:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '0':	goto yy126;
	case '1':	goto yy128;
	case '2':	goto yy129;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy130;
	default:	goto yy43;
	}
yy109:
	yyaccept = 0;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '.':	goto yy108;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy88;
	default:	goto yy43;
	}
yy110:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy131;
	case ':':	goto yy94;
	default:	goto yy54;
	}
yy111:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy132;
	case ':':	goto yy133;
	default:	goto yy54;
	}
yy112:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy134;
	case '1':	goto yy135;
	case '2':	goto yy136;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy137;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy138;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy113:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy139;
	case ':':	goto yy114;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy114:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy138;
	default:	goto yy54;
	}
yy115:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy140;
	case ':':	goto yy114;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy139;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy116:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy140;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy139;
	case ':':	goto yy114;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy117:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy139;
	case ':':	goto yy114;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy118:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy141;
	default:	goto yy54;
	}
yy119:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy141;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy121;
	default:	goto yy54;
	}
yy120:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy141;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy121;
	case '5':	goto yy142;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy118;
	default:	goto yy54;
	}
yy121:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy141;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy118;
	default:	goto yy54;
	}
yy122:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy143;
	case ':':	goto yy102;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy123:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy143;
	case ':':	goto yy102;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy124:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':	goto yy143;
	case ':':	goto yy102;
	case ']':	goto yy82;
	case 'f':	goto yy144;
	default:	goto yy54;
	}
yy125:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy75;
	case ':':	goto yy146;
	default:	goto yy54;
	}
yy126:
	yyaccept = 2;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy43;
	default:	goto yy127;
	}
yy127:
#line 99 "url_parser.re"
	{
    int len = url_str - src - pos;
    url->host->type = IPV4ADDR;
    char *name = get_lex(src, &pos, len);
    strncpy (url->host->name, name, HOST_MAX_LEN < len + 1 ? HOST_MAX_LEN : len + 1);
    free (name);
    goto hier_part_port;
  }
#line 2655 "url_parser.c"
yy128:
	yyaccept = 2;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy43;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy130;
	default:	goto yy127;
	}
yy129:
	yyaccept = 2;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy43;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy130;
	case '5':	goto yy147;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy126;
	default:	goto yy127;
	}
yy130:
	yyaccept = 2;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy43;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy126;
	default:	goto yy127;
	}
yy131:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy94;
	default:	goto yy54;
	}
yy132:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy148;
	case ':':	goto yy133;
	default:	goto yy54;
	}
yy133:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy149;
	case ':':	goto yy150;
	default:	goto yy54;
	}
yy134:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy151;
	case ':':	goto yy152;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy135:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy153;
	case ':':	goto yy152;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy151;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy136:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy153;
	case '5':	goto yy154;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy155;
	case ':':	goto yy152;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy151;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy137:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy155;
	case ':':	goto yy152;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy151;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy138:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy151;
	case ':':	goto yy152;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy139:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy156;
	case ':':	goto yy114;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy140:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy156;
	case ':':	goto yy114;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy141:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy157;
	case '1':	goto yy158;
	case '2':	goto yy159;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy160;
	default:	goto yy54;
	}
yy142:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy141;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy118;
	default:	goto yy54;
	}
yy143:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy102;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy144:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy161;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy145:
	yych = *++url_str;
	switch (yych) {
	case ']':	goto yy54;
	default:	goto yy163;
	}
yy146:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy164;
	case '1':	goto yy165;
	case '2':	goto yy166;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy168;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy147:
	yyaccept = 2;
	yych = *(marker = ++url_str);
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '6':
	case '7':
	case '8':
	case '9':
	case ';':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy43;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy126;
	default:	goto yy127;
	}
yy148:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy169;
	case ':':	goto yy133;
	default:	goto yy54;
	}
yy149:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy170;
	case ':':	goto yy171;
	default:	goto yy54;
	}
yy150:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy172;
	case '1':	goto yy173;
	case '2':	goto yy174;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy175;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy176;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy151:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy177;
	case ':':	goto yy152;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy152:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy176;
	default:	goto yy54;
	}
yy153:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy178;
	case ':':	goto yy152;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy177;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy154:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy178;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy177;
	case ':':	goto yy152;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy155:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy177;
	case ':':	goto yy152;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy156:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy114;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy157:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy179;
	default:	goto yy54;
	}
yy158:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy179;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy160;
	default:	goto yy54;
	}
yy159:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy179;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy160;
	case '5':	goto yy180;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy157;
	default:	goto yy54;
	}
yy160:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy179;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy157;
	default:	goto yy54;
	}
yy161:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy181;
	case '1':	goto yy96;
	case '2':	goto yy97;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy98;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy99;
	default:	goto yy54;
	}
yy162:
	++url_str;
	yych = *url_str;
yy163:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy162;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy164:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy182;
	case ':':	goto yy183;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy165:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy184;
	case ':':	goto yy183;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy182;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy166:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy184;
	case '5':	goto yy185;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy186;
	case ':':	goto yy183;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy182;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy167:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy186;
	case ':':	goto yy183;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy182;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy168:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy182;
	case ':':	goto yy183;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy169:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy133;
	default:	goto yy54;
	}
yy170:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy187;
	case ':':	goto yy171;
	default:	goto yy54;
	}
yy171:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy188;
	case ':':	goto yy189;
	default:	goto yy54;
	}
yy172:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy190;
	case ':':	goto yy191;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy173:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy192;
	case ':':	goto yy191;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy190;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy174:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy192;
	case '5':	goto yy193;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy194;
	case ':':	goto yy191;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy190;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy175:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy194;
	case ':':	goto yy191;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy190;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy176:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy190;
	case ':':	goto yy191;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy177:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy195;
	case ':':	goto yy152;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy178:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy195;
	case ':':	goto yy152;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy179:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy196;
	case '1':	goto yy197;
	case '2':	goto yy198;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy199;
	default:	goto yy54;
	}
yy180:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy179;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy157;
	default:	goto yy54;
	}
yy181:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy113;
	case ':':	goto yy200;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy182:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy201;
	case ':':	goto yy183;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy183:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy202;
	default:	goto yy54;
	}
yy184:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy203;
	case ':':	goto yy183;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy201;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy185:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy203;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy201;
	case ':':	goto yy183;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy186:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy201;
	case ':':	goto yy183;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy187:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy204;
	case ':':	goto yy171;
	default:	goto yy54;
	}
yy188:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy205;
	case ':':	goto yy206;
	default:	goto yy54;
	}
yy189:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy207;
	case '1':	goto yy208;
	case '2':	goto yy209;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy210;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy211;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy190:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy212;
	case ':':	goto yy191;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy191:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy211;
	default:	goto yy54;
	}
yy192:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy213;
	case ':':	goto yy191;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy212;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy193:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy213;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy212;
	case ':':	goto yy191;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy194:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy212;
	case ':':	goto yy191;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy195:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy152;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy196:
	yych = *++url_str;
	switch (yych) {
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy197:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy199;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy198:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy199;
	case '5':	goto yy214;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy196;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy199:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy196;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy200:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy215;
	case '1':	goto yy135;
	case '2':	goto yy136;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy137;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy138;
	default:	goto yy54;
	}
yy201:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy216;
	case ':':	goto yy183;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy202:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy217;
	case ':':	goto yy218;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy203:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy216;
	case ':':	goto yy183;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy204:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy171;
	default:	goto yy54;
	}
yy205:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy219;
	case ':':	goto yy206;
	default:	goto yy54;
	}
yy206:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy220;
	case ':':	goto yy221;
	default:	goto yy54;
	}
yy207:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy208:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy224;
	case ':':	goto yy223;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy209:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy224;
	case '5':	goto yy225;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy226;
	case ':':	goto yy223;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy210:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy226;
	case ':':	goto yy223;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy211:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy212:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy227;
	case ':':	goto yy191;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy213:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy227;
	case ':':	goto yy191;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy214:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy196;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy215:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy151;
	case ':':	goto yy228;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy216:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case ':':	goto yy183;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy217:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy229;
	case ':':	goto yy218;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy218:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy230;
	default:	goto yy54;
	}
yy219:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy231;
	case ':':	goto yy206;
	default:	goto yy54;
	}
yy220:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy232;
	case ':':	goto yy233;
	default:	goto yy54;
	}
yy221:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy234;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy222:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy235;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy223:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy234;
	default:	goto yy54;
	}
yy224:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy236;
	case ':':	goto yy223;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy235;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy225:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy236;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy235;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy226:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy235;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy227:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy191;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy228:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy237;
	case '1':	goto yy173;
	case '2':	goto yy174;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy175;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy176;
	default:	goto yy54;
	}
yy229:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy238;
	case ':':	goto yy218;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy230:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy239;
	case ':':	goto yy240;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy231:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy206;
	default:	goto yy54;
	}
yy232:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy241;
	case ':':	goto yy233;
	default:	goto yy54;
	}
yy233:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy242;
	case ':':	goto yy243;
	default:	goto yy54;
	}
yy234:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy244;
	case ':':	goto yy245;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy235:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy246;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy236:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy246;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy237:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy190;
	case ':':	goto yy247;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy238:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case ':':	goto yy218;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy239:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy248;
	case ':':	goto yy240;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy240:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy249;
	default:	goto yy54;
	}
yy241:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy250;
	case ':':	goto yy233;
	default:	goto yy54;
	}
yy242:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy251;
	case ':':	goto yy252;
	default:	goto yy54;
	}
yy243:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy253;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy244:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy254;
	case ':':	goto yy245;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy245:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy253;
	default:	goto yy54;
	}
yy246:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy247:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy255;
	case '1':	goto yy208;
	case '2':	goto yy209;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy210;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy211;
	default:	goto yy54;
	}
yy248:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy256;
	case ':':	goto yy240;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy249:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy257;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy250:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy233;
	default:	goto yy54;
	}
yy251:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy258;
	case ':':	goto yy252;
	default:	goto yy54;
	}
yy252:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy253;
	case ':':	goto yy196;
	default:	goto yy54;
	}
yy253:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy259;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy254:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy260;
	case ':':	goto yy245;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy255:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	case ':':	goto yy261;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy256:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case ':':	goto yy240;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy257:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy262;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy258:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy263;
	case ':':	goto yy252;
	default:	goto yy54;
	}
yy259:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy264;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy260:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy245;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy261:
	yych = *++url_str;
	switch (yych) {
	case '0':	goto yy265;
	case '1':	goto yy266;
	case '2':	goto yy267;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy268;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy234;
	default:	goto yy54;
	}
yy262:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy269;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy263:
	yych = *++url_str;
	switch (yych) {
	case ':':	goto yy252;
	default:	goto yy54;
	}
yy264:
	yych = *++url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy196;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy265:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy244;
	case ':':	goto yy245;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy266:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy270;
	case ':':	goto yy245;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy244;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy267:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':	goto yy270;
	case '5':	goto yy271;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy272;
	case ':':	goto yy245;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy244;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy268:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy272;
	case ':':	goto yy245;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy244;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy269:
	yych = *++url_str;
	switch (yych) {
	case '%':	goto yy145;
	case ':':	goto yy223;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy270:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy273;
	case ':':	goto yy245;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy254;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy271:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy273;
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy254;
	case ':':	goto yy245;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy272:
	yych = *++url_str;
	switch (yych) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy254;
	case ':':	goto yy245;
	case ']':	goto yy82;
	default:	goto yy54;
	}
yy273:
	++url_str;
	switch ((yych = *url_str)) {
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy260;
	case ':':	goto yy245;
	case ']':	goto yy82;
	default:	goto yy54;
	}
}
#line 135 "url_parser.re"


hier_part_port:

#line 6540 "url_parser.c"
{
	unsigned char yych;
	yych = *url_str;
	switch (yych) {
	case 0x00:	goto yy277;
	case ':':	goto yy279;
	default:	goto yy276;
	}
yy276:
#line 143 "url_parser.re"
	{ goto hier_part_path; }
#line 6552 "url_parser.c"
yy277:
	++url_str;
#line 139 "url_parser.re"
	{
    url->valid = 1;
    return 1;
  }
#line 6560 "url_parser.c"
yy279:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy279;
	default:	goto yy281;
	}
yy281:
#line 144 "url_parser.re"
	{
    pos++; // shift ":"
    int len = url_str - src - pos;
    char *port = get_lex(src, &pos, len);
    url->port = atoi (port);
    free (port);
    goto hier_part_path;
  }
#line 6587 "url_parser.c"
}
#line 152 "url_parser.re"


hier_part_path:

#line 6594 "url_parser.c"
{
	unsigned char yych;
	yych = *url_str;
	switch (yych) {
	case 0x00:	goto yy284;
	case '/':	goto yy288;
	default:	goto yy286;
	}
yy284:
	++url_str;
#line 156 "url_parser.re"
	{
    url->valid = 1;
    return 1;
  }
#line 6610 "url_parser.c"
yy286:
	++url_str;
#line 160 "url_parser.re"
	{goto query_frag;}
#line 6615 "url_parser.c"
yy288:
	marker = ++url_str;
	yych = *url_str;
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy288;
	case '%':	goto yy291;
	default:	goto yy290;
	}
yy290:
#line 161 "url_parser.re"
	{
    int len = url_str - src - pos;
    url->path = get_lex(src, &pos, len);
    goto query_frag;
  }
#line 6710 "url_parser.c"
yy291:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy293;
	default:	goto yy292;
	}
yy292:
	url_str = marker;
	goto yy290;
yy293:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy288;
	default:	goto yy292;
	}
}
#line 166 "url_parser.re"


query_frag:

#line 6776 "url_parser.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *url_str;
	switch (yych) {
	case 0x00:	goto yy296;
	case '#':	goto yy300;
	case '?':	goto yy303;
	default:	goto yy298;
	}
yy296:
	++url_str;
#line 171 "url_parser.re"
	{
    url->valid = 1;
    return 1;
  }
#line 6794 "url_parser.c"
yy298:
	++url_str;
#line 170 "url_parser.re"
	{ return 0; }
#line 6799 "url_parser.c"
yy300:
	yyaccept = 0;
	marker = ++url_str;
	yych = *url_str;
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy300;
	case '%':	goto yy306;
	default:	goto yy302;
	}
yy302:
#line 181 "url_parser.re"
	{
    pos++; // shift "#"
    int len = url_str - src - pos;
    url->fragment = get_lex(src, &pos, len);
    return 1;
  }
#line 6897 "url_parser.c"
yy303:
	yyaccept = 1;
	marker = ++url_str;
	yych = *url_str;
	switch (yych) {
	case '!':
	case '$':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '=':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '~':	goto yy303;
	case '%':	goto yy308;
	default:	goto yy305;
	}
yy305:
#line 175 "url_parser.re"
	{
    pos++; // shift "?"
    int len = url_str - src - pos;
    url->query = get_lex(src, &pos, len);
    goto query_frag;
  }
#line 6995 "url_parser.c"
yy306:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy309;
	default:	goto yy307;
	}
yy307:
	url_str = marker;
	if (yyaccept == 0) {
		goto yy302;
	} else {
		goto yy305;
	}
yy308:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy310;
	default:	goto yy307;
	}
yy309:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy300;
	default:	goto yy307;
	}
yy310:
	++url_str;
	yych = *url_str;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy303;
	default:	goto yy307;
	}
}
#line 187 "url_parser.re"

  return 0;
}

URL *url_create ()
{
  URL *url = (URL*) malloc (sizeof(URL));
  url->scheme   = NULL;
  url->userinfo = NULL;
  url->host = (Host*) malloc (sizeof(Host));
  url->port = 0;
  url->path = NULL;
  url->query = NULL;
  url->fragment = NULL;
  url->valid = 0;
  return url;
}

void url_free (URL *url)
{
  if (url->scheme) free (url->scheme);
  if (url->userinfo) free (url->userinfo);
  if (url->host) free (url->host);
  if (url->path) free (url->path);
  if (url->query) free (url->query);
  if (url->fragment) free (url->fragment);
  free (url);
}

char * get_lex(const char *url, int *from, int len)
{
  char *res = (char *) malloc (len + 1);
  int i;
  for (i = 0; i < len; i++)
  {
    res[i] = url[*from + i];
  }
  res[i] = '\0';
  *from += len;
  return res;
}
